author: Rutr
description: Easier method to set the groups of players
main: pl.azpal.azrank.AZRank
name: AZRank
version: 1.2.2
softdepend: [PermissionsEx, bPermissions, GroupManager]
commands:
  azrank:
    description: Gets info about player or Sets the rank of a user
    usage: "Usage: /<command> <player> [group] [time]"
    aliases: [rank, rankset, setgroup, player, setrank]
  azrankreload:
    description: Reloads SetRankPEX
    usage: "Usage: /<command>"
    aliases: [reloadazrank, rankreload, azrankreload]
  restoregroup:
    description: restores the previous group
    usage: "Usage: /<command> <player>"
    aliases: [unsetrank, ungroup, unrank]
  azranks:
    description: display a list of user having temp group
    usage: "Usage: /<command> <player>"
    aliases: [tempranks, tempgroups]
  azextend:
    description: prolongs the duration of the rank
    usage: "Usage: /<command> <player> [group] <time>"
    aliases: [ezext, extendrank, azprolong]
permissions:
  azrank.*:
    description: Allows permission to all SetRankPEX features
    children:
      azrank.setrank.*: true
      azrank.reload: true
      azrank.restore: true
  azrank.setrank.*:
    description: Allows permission to set a user's rank to anything
    children:
      azrank.setrank.group: true
  azrank.setrank.group:
    description: Allows permission to set a user's rank to the given group
  azrank.reload:
    description: Allows permission to reload SetRankPEX
  azrank.restore:
    description: Allows permission to restore group