author: Rutr
description: Give groups for specified time
main: pl.azpal.azrank.AZRank
name: AZRank
version: 1.3.b1
softdepend: [Vault,PermissionsEx]
commands:
  azplayer:
    description: List player groups
    usage: "Usage: /<command> <player>"
    aliases: [azrank]
  azsetgroup:
    description: Set <player> groups to <group> for [time] or permanently
    usage: "Usage: /<command> <player> <group> [[-s] time]"
    aliases: [azsetrank]
  azaddgroup:
    description: Add <player> to <group> for [time] or permanently
    usage: "Usage: /<command> <player> <group> [[-s] time]"
    aliases: [azaddrank]
  azremgroup:
    description: Remove <player> from <group>
    usage: "Usage: /<command> <player> <group>"
    aliases: [azremrank,azremovegroup,azremoverank]
  azrankreload:
    description: Reloads SetRankPEX
    usage: "Usage: /<command>"
    aliases: [reloadazrank, rankreload, azrankreload]
  restoregroup:
    description: restores the previous group
    usage: "Usage: /<command> <player>"
    aliases: [unsetrank, ungroup, unrank]
  azranks:
    description: display a list of user having temp group
    usage: "Usage: /<command> <player>"
    aliases: [tempranks, tempgroups]
  azextend:
    description: prolongs the duration of the rank
    usage: "Usage: /<command> <player> [group] <time>"
    aliases: [azext]
permissions:
  azrank.*:
    description: Allows permission to all SetRankPEX features
    children:
      azrank.setrank.*: true
      azrank.reload: true
      azrank.restore: true
  azrank.setrank.*:
    description: Allows permission to set a user's rank to anything
    children:
      azrank.setrank.group: true
  azrank.setrank.group:
    description: Allows permission to set a user's rank to the given group
  azrank.reload:
    description: Allows permission to reload SetRankPEX
  azrank.restore:
    description: Allows permission to restore group